django_app/app/reservas/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('webapp.urls')),
    path('admin/', admin.site.urls),
]

django_app/app/reviews/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('home/', include('webapp.urls')),
    path('admin/', admin.site.urls),
]

django_app/app/webapp/urls.py
from django.urls import path

from . import views

app_name = 'webapp'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('login/', views.login, name = 'login'),
    path('registrarse/', views.registrarse, name = 'registrarse'),
    path('reservas/', views.reservas, name = 'reservas'),
]

django_app/app/webapp/models.py
import datetime

from django.db import models
from django.utils import timezone

class Extension(models.Model):
    id_extension = models.CharField(max_length=3, primary_key=True)
    extension = models.CharField(max_length=200)

    def __str__(self):
        return self.id_extension + " - " + self.extension

class Reservante(models.Model):
    nombre = models.TextField(max_length=200)
    email = models.EmailField()
    numero_telefono = models.CharField(max_length=8)
    extension = models.ForeignKey(Extension, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class Reserva(models.Model):
    propietario = models.ForeignKey(Reservante, on_delete=models.CASCADE)
    clave = models.CharField(max_length=50)
    fecha_reserva = models.DateField()
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()

    def not_reservable(self):
        now = timezone.now()
        return self.fecha_reserva < now

django_app/app/webapp/views.py
from django.shortcuts import render, get_object_or_404

from .models import Extension, Reservante, Reserva

def index(request):
    context = {'extensiones': Extension.objects.all()}
    return render(request, 'webapp/salas.html', context)

def login(request):
    return render(request, 'webapp/login.html')

def registrarse(request):
    return render(request, 'webapp/register.html')

def reservas(request):
    if request.method == 'POST':
        try:
            reservante = Reservante(
                nombre=request.POST['propietario'],
                email=request.POST['email'],
                numero_telefono=int(request.POST['numero']),
                extension=Extension.objects.get(pk=request.POST['extension'])
            )
            reservante.save()
            reserva = Reserva(
                propietario=get_object_or_404(Reservante, pk=reservante.id),
                clave=request.POST['password'],
                fecha_reserva=request.POST['fecha_reserva'],
                hora_inicio=request.POST['hora_inicio'],
                hora_fin=request.POST['hora_fin']
            )
            reserva.save()
        except Exception as error:
            reservante = Reservante.objects.get(nombre=request.POST['propietario'])
            reservante.delete()
            data = {'error_message': error}
            return render(request, 'webapp/reservas.html', data)
    context = {
        'reservas': Reserva.objects.all()
    }
    return render(request, 'webapp/reservas.html', context)

django_app/app/webapp/templates/webapp/footer.html
<footer>
    <div>
        Desarrollada por Jos&eacute; Osorio &copy; Derechos reservados 2018
    </div>
</footer>

django_app/app/webapp/templates/webapp/header.html
<div class="title_bar">
    <div class="titulo">PDC135 - Reserva de salas de conferencia</div>
</div>
<div class="bar">
    <ul>
        <li>
            <a href="{% url 'webapp:index' %}">Reservar</a>
        </li>
        <li>
            <a href="{% url 'webapp:reservas' %}">Ver reservas</a>
        </li>
        <li>
            <a href="/about">Acerca de</a>
        </li>
    </ul>
</div>

django_app/app/webapp/templates/webapp/login.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'webapp/css/login.css' %}">
    <title>Login</title>
</head>
<body>
    <header>
        <img id="ues_logo" src="{% static 'webapp/img/ues_logo.png' %}" alt="Logo UES" width="69x" height="87px">
        <div id="titulo_header">
            Universidad de El Salvador<br>
            Facultad Multidisciplinaria de Occidente<br>
            Ingenier&iacute;a de Sistemas Inform&aacute;ticos<br>
            Protocolos de Comunicaci&oacute;n
        </div>
        <button id="btn_registrarse">Registrarse</button>
    </header>

    <h1 id="titulo_pagina">Reservaci&oacute;n de salas de conferencia por llamada</h1>

    <div class="contenedor" style="width: 420px;">
        <p id="form_title">Iniciar Sesi&oacute;n</p>
        <form id="login_form" action="#">
            <div class="form_elements">
                <label class="form_labels" for="email">Correo Electr&oacute;nico:</label>
                <input class="form_inputs" id="email" type="email">
                <label class="form_labels" for="password">Contrase&ntilde;a:</label>
                <input class="form_inputs" id="password" type="password">
                <input type="submit" id="btn_ingresar" value="Ingresar">
            </div>
        </form>
    </div>
    
    {% include 'webapp/footer.html' %}
    <script src="{% static 'webapp/js/login.js' %}">
    </script>
</body>
</html>

django_app/app/webapp/templates/webapp/register.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'webapp/css/main.css' %}" />
        <title>Registrarse</title>
    </head>
    <body>
        <header>
            <div>
                <h1>P&aacute;gina de rgistro</h1>
            </div>
        </header>
        <footer>
            <div>
                Desarrollada por Jos&eacute; Osorio &copy; Derechos reservados 2018
            </div>
        </footer>
    </body>
</html>

django_app/app/webapp/templates/webapp/reservas.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'webapp/css/reservas.css' %}">
    <title>Ver reservas</title>
</head>
<body>
    {% include "webapp/header.html" %}
    {% if error_message %}<p><strong style="color: black;">{{ error_message }}</strong></p>{% endif %}
    <div class="contenedor" style="width: 1000px">
        <table class="table">
            <thead>
                <tr>
                    <td style="border-top-left-radius: 7px">Reservante</td>
                    <td>Email</td>
                    <td>Fecha de Reserva</td>
                    <td>Hora Inicio</td>
                    <td style="border-top-right-radius: 7px">Hora Fin</td>
                </tr>
            </thead>
            {% for res in reservas %}
            <tr>
                <td>{{ res.propietario.nombre }}</td>
                <td>{{ res.propietario.email }}</td>
                <td>{{ res.fecha_reserva }}</td>
                <td>{{ res.hora_inicio }}</td>
                <td>{{ res.hora_fin }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</body>
</html>

django_app/app/webapp/templates/webapp/salas.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'webapp/css/salas.css' %}">
    <title>Reserva de Salas</title>
</head>
<body>
    {% include 'webapp/header.html' %}

    <div class="contenedor" style="width: 750px;">
        <p class="form_title" style="text-align: center;">Reserva de Sala</p>
        <form id='form_reservas' action="{% url 'webapp:reservas' %}" method="POST">
            {% csrf_token %}
            <div class="form_element" style="margin-top: 10px;">
                <label class="form_labels" for="propietario">Nombre del que reserva: </label>
                <input class="form_inputs" type="text" name="propietario" required>
            </div>
            <div class="form_element">
                <label class="form_labels" for="email">Correo electr&oacute;nico: </label>
                <input class="form_inputs" type="email" name="email" required>
            </div>
            <div class="form_element">
                <label class="form_labels" for="numero">Tel&eacute;fono: </label>
                <input class="number" type="text" name="numero" maxlength="8" required>
                <label class="form_labels" for="extension">Extensi&oacute;n: </label>
                <select name="extension" id="extension">
                    {% if  extensiones %}
                        {% for ext in extensiones %}
                            <option value="{{ ext.id_extension }}">{{ ext }}</option>
                        {% endfor %}
                    {% endif %}
                </select>
            </div>
            <div class="form_element">
                <label class="form_labels" for="password">Contrase&ntilde;a de la sala: </label>
                <input class="form_inputs" type="password" name="password" required>
            </div>
            <div class="form_element">
                <label class="form_labels" for="fecha_reserva">Fecha a reservar: </label>
                <input class="fecha" type="date" name="fecha_reserva" required>
                <label class="form_labels" for="hora_inicio">Inicio: </label>
                <input class="hora" type="time" name="hora_inicio" required>
                <label class="form_labels" for="hora_fin">Fin: </label>
                <input class="hora" type="time" name="hora_fin" required>
            </div>
            <div class="form_element">
                <input id='submit' class="btn_reservar" type="submit" value="Reservar">
            </div>
        </form>
        <script src="{% static 'webapp/js/reservas.js' %}"></script> 
    </div>
</body>
</html>